# Generated by Django 5.1.8 on 2025-04-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ausencia',
            name='justificada',
            field=models.BooleanField(default=False),
        ),
    ]
