# Generated by Django 5.1.8 on 2025-04-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0002_alter_aula_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='hora',
            field=models.CharField(max_length=2),
        ),
    ]
