# Generated by Django 5.1.8 on 2025-04-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0003_alter_horario_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='hora',
            field=models.IntegerField(default=1),
        ),
    ]
